// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"context"
	"fmt"
	"os"

	"github.com/jocall3/1231-cli/internal/apiquery"
	"github.com/jocall3/1231-cli/internal/requestflag"
	"github.com/jocall3/go"
	"github.com/jocall3/go/option"
	"github.com/tidwall/gjson"
	"github.com/urfave/cli/v3"
)

var corporateComplianceAuditsRequest = cli.Command{
	Name:  "request",
	Usage: "Initiates an AI-powered compliance audit for a specific period or scope,\ngenerating a comprehensive report detailing adherence to regulatory frameworks,\ninternal policies, and flagging potential risks.",
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "audit-scope",
			Usage:    "The scope of the audit (e.g., all transactions, specific accounts).",
			BodyPath: "auditScope",
		},
		&requestflag.Flag[any]{
			Name:     "end-date",
			Usage:    "End date for the audit period (inclusive).",
			BodyPath: "endDate",
		},
		&requestflag.Flag[[]string]{
			Name:     "regulatory-framework",
			Usage:    "List of regulatory frameworks against which to audit.",
			BodyPath: "regulatoryFrameworks",
		},
		&requestflag.Flag[any]{
			Name:     "start-date",
			Usage:    "Start date for the audit period (inclusive).",
			BodyPath: "startDate",
		},
		&requestflag.Flag[any]{
			Name:     "additional-context",
			Usage:    "Optional: Any additional context or specific areas of concern for the AI.",
			BodyPath: "additionalContext",
		},
	},
	Action:          handleCorporateComplianceAuditsRequest,
	HideHelpCommand: true,
}

var corporateComplianceAuditsRetrieveReport = cli.Command{
	Name:  "retrieve-report",
	Usage: "Retrieves the full report generated by an AI-driven compliance audit.",
	Flags: []cli.Flag{
		&requestflag.Flag[any]{
			Name: "audit-id",
		},
	},
	Action:          handleCorporateComplianceAuditsRetrieveReport,
	HideHelpCommand: true,
}

func handleCorporateComplianceAuditsRequest(ctx context.Context, cmd *cli.Command) error {
	client := jocall3.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := jocall3.CorporateComplianceAuditRequestParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Corporate.Compliance.Audits.Request(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, "corporate:compliance:audits request", obj, format, transform)
}

func handleCorporateComplianceAuditsRetrieveReport(ctx context.Context, cmd *cli.Command) error {
	client := jocall3.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("audit-id") && len(unusedArgs) > 0 {
		cmd.Set("audit-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Corporate.Compliance.Audits.GetReport(ctx, interface{}(cmd.Value("audit-id").(any)), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, "corporate:compliance:audits retrieve-report", obj, format, transform)
}
